name: Docker Container

on:
 # run it on push to the default repository branch
 push:
   branches: [main]
   tags:
     - '*'

 pull_request:


jobs:
  build-and-push-docker-image:
    name: Build circhemy CLI docker image and push to repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push GitHub container registry
        uses: docker/build-push-action@v4
        with:
          context: ./docker/
          tags: |
            ghcr.io/jakobilab/circhemy/circhemy-cli:main
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}